services:
  mysql:
    image: mysql:8.0
    container_name: airport-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airport
      MYSQL_USER: airport
      MYSQL_PASSWORD: airport
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  redis:
    image: redis:7.2
    container_name: airport-redis
    ports:
      - "6379:6379"
    restart: always

  zookeeper:
    image: zookeeper:3.8
    container_name: airport-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: airport-kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    restart: always